/**
 * Auto-generated third-party integration API (`/api/v1`).
 *
 * Every route here is derived from the active inverter profile's entity
 * catalog — the catalog, the per-entity read routes, and one validated write
 * route per writable entity are all generated by looping {@link profile.metrics}.
 * Adding a metric to a profile (or installing a new inverter package) extends
 * this API and its OpenAPI docs with zero route code.
 *
 * Auth: guarded by `API_KEYS` (see the guard below). This is the external
 * surface; the web app's own session-authed endpoints live in `index.ts`.
 */

import { auth } from "@SunReye/auth";
import { env } from "@SunReye/env/server";
import { entityConstraint, writableMetrics } from "@SunReye/inverter-core";
import { Elysia, t } from "elysia";
import { entityErrorResponse } from "./entity-errors";
import { rangeNote, valueSchema } from "./entity-schema";
import { queryRawHistory, queryRollup } from "../shared/history";
import { aggregateOfMetric, isRefusal, plantFoldFor } from "../shared/plant-read";
import { type PlantMember, parseSeriesSource } from "../shared/plant-source";
import type { ProfileContext } from "./inverter";
import { WriteRejectedError } from "./write-rejected";

/** Elysia's `status` helper, as narrowly as this file needs it. */
type StatusFn = (code: 400, body: { error: string }) => unknown;
import { log } from "../shared/logging";
import { liveState } from "../shared/state";

const logger = log("api");

/** Extract the presented key from either `Authorization: Bearer` or `x-api-key`. */
function extractApiKey(request: Request): string | undefined {
  const header = request.headers.get("authorization");
  const bearer = header?.toLowerCase().startsWith("bearer ") ? header.slice(7).trim() : undefined;
  return bearer ?? request.headers.get("x-api-key") ?? undefined;
}

/** Dev convenience: with no static keys configured, the surface is open. */
const openInDevelopment = (keys: readonly string[]): boolean =>
  keys.length === 0 && env.NODE_ENV !== "production";

/**
 * Whether the presented key authorizes the request: the static `API_KEYS`
 * allow-list, or a managed (DB-backed) key issued through the Better Auth API
 * Key plugin. `verifyApiKey` never throws for an unknown key, but adapter/DB
 * errors are caught too so a transient failure can't accidentally authorize.
 */
async function keyAccepted(provided: string, keys: readonly string[]): Promise<boolean> {
  if (keys.includes(provided)) return true;
  const res = await auth.api.verifyApiKey({ body: { key: provided } }).catch(() => null);
  return res?.valid === true;
}

/**
 * Why a request was rejected. With neither static keys nor a presented
 * credential the operator simply hasn't configured static access (managed keys
 * are still accepted above); anything else is a bad or missing key.
 */
function denial(keys: readonly string[], provided: string | undefined) {
  const unconfigured = keys.length === 0 && provided === undefined;
  return {
    status: 401,
    error: unconfigured ? "API access is not configured" : "Invalid or missing API key",
  };
}

/**
 * Reject requests without a valid API key. Two credential sources are accepted:
 * the static `API_KEYS` env allow-list and admin-issued managed keys (see
 * {@link keyAccepted}). Empty `API_KEYS` stays open in development (local
 * convenience) but fails closed in production, so the public surface is never
 * accidentally unauthenticated.
 */
async function checkApiKey(request: Request): Promise<{ status: number; error: string } | null> {
  const keys = env.API_KEYS;
  const provided = extractApiKey(request);
  if (openInDevelopment(keys)) return null;
  if (provided !== undefined && (await keyAccepted(provided, keys))) return null;
  return denial(keys, provided);
}

/** Injected transport dependencies (keeps this module free of the singleton). */
export interface EntitiesApiDeps {
  /**
   * The active profile context (manifest, catalog), resolved at boot — or `null`
   * in onboarding-only boot, when there's no profile and thus no entity surface.
   */
  ctx: ProfileContext | null;
  /**
   * The plant's history members, for `source=plant` on the history route.
   * Optional: a caller with no plant (the unit suite) reads devices only, and a
   * plant request then folds an empty set — "no data", never a throw.
   */
  members?: () => Promise<readonly PlantMember[]>;
  write(key: string, value: number): Promise<void>;
}

/** Mount the generated `/api/v1` integration API onto an Elysia app. */
export function entitiesApi(deps: EntitiesApiDeps) {
  // Onboarding-only boot: no active profile, so no entities to generate. Mount an
  // empty group so the composition root can `.use()` it unconditionally.
  if (!deps.ctx) return new Elysia({ prefix: "/api/v1", name: "entities" });
  const { profile, manifest, metaByKey } = deps.ctx;
  const app = new Elysia({ prefix: "/api/v1", name: "entities" })
    .error(({ error, set }) => {
      // Preserve the status of known request errors; sanitize everything else to
      // a generic 500 so internal stack traces never leak to third parties. The
      // mapping is ./entity-errors, which is where it can be tested.
      const failure = entityErrorResponse(error);
      if (failure.log !== null) logger.error("{error}", { error: failure.log });
      set.status = failure.status;
      return failure.body;
    })
    .beforeHandle(async ({ request, set }) => {
      const denied = await checkApiKey(request);
      if (denied) {
        set.status = denied.status;
        return { error: denied.error };
      }
    })
    // Entity catalog: identity, label, unit, kind, role, topic, writability,
    // bounds/enum. The discovery endpoint a consumer reads first.
    .get(
      "/entities",
      {
        detail: {
          tags: ["Entities"],
          summary: "List entities",
          description: "Full catalog of entities the active inverter exposes.",
        },
      },
      () => ({
        id: manifest.id,
        name: manifest.name,
        manufacturer: manifest.manufacturer,
        capabilities: manifest.capabilities,
        entities: manifest.metrics,
      }),
    )
    // Current value of every entity in one snapshot (from the live poll cache).
    .get(
      "/state",
      {
        detail: {
          tags: ["Entities"],
          summary: "Current state",
          description: "Latest value of every entity from the most recent poll.",
        },
      },
      ({ set }) => {
        const sample = liveState.latest;
        if (!sample) {
          set.status = 503;
          return { error: "No sample available yet" };
        }
        return { time: sample.time, inverterId: sample.inverterId, values: sample.metrics };
      },
    )
    // One entity's metadata plus its latest value.
    .get(
      "/entities/:key",
      {
        params: t.Object({ key: t.String() }),
        detail: {
          tags: ["Entities"],
          summary: "Get entity",
          description: "Metadata and latest value for a single entity.",
        },
      },
      ({ params, set }) => {
        const meta = metaByKey.get(params.key);
        if (!meta) {
          set.status = 404;
          return { error: `Unknown entity: ${params.key}` };
        }
        return { ...meta, value: liveState.latest?.metrics[params.key] ?? null };
      },
    )
    // Time series for one entity. Raw samples by default; pass `bucket` to read
    // the pre-aggregated TimescaleDB rollups (cheap over long windows).
    .get(
      "/entities/:key/history",
      {
        params: t.Object({ key: t.String() }),
        query: t.Object({
          hours: t.Number({ default: 24, minimum: 1 }),
          limit: t.Number({ default: 5000, minimum: 1, maximum: 50000 }),
          bucket: t.Optional(t.Union([t.Literal("minute"), t.Literal("hour"), t.Literal("day")])),
          source: t.Optional(t.String()),
          inverterId: t.Optional(t.String()),
        }),
        detail: {
          tags: ["Entities"],
          summary: "Entity history",
          description:
            "Time series for one entity: raw samples, or aggregated rollups when `bucket` is set. " +
            "`source` is `plant` (the members folded by the entity's role) or a device slug.",
        },
      },
      async ({ params, query, set }) => {
        if (!metaByKey.has(params.key)) {
          set.status = 404;
          return { error: `Unknown entity: ${params.key}` };
        }
        // Absent, the profile id — the pre-#202 spelling, which the identity
        // boundary still resolves to the one device running that profile.
        const req = parseSeriesSource(query) ?? { kind: "device" as const, slug: profile.id };
        const members = req.kind === "plant" ? await (deps.members?.() ?? Promise.resolve([])) : [];
        const args = plantFoldFor(req, members, params.key, aggregateOfMetric(metaByKey));
        if (isRefusal(args)) {
          set.status = 422;
          return args;
        }
        const since = new Date(Date.now() - query.hours * 60 * 60 * 1000);
        const base = { metric: params.key, since, limit: query.limit, ...args };
        return query.bucket
          ? queryRollup({ ...base, bucket: query.bucket })
          : queryRawHistory(base);
      },
    );

  // One validated write route per writable entity. Bounds/enum come from the
  // entity's metadata, so each route documents (and enforces) exactly what it
  // accepts. We fold routes into the chain (capturing each `.put()` return, not
  // calling it as a statement) so they reach `getGlobalRoutes()` and therefore
  // the OpenAPI spec. Precise per-route types are intentionally dropped here —
  // these routes are consumed by third parties via OpenAPI, not Eden.
  return writableMetrics(profile).reduce<Elysia>(
    (acc, metric) => {
      const constraint = entityConstraint(metric);
      const accepts = rangeNote(constraint, metric.unit);
      return acc.put(
        `/entities/${metric.key}`,
        {
          body: t.Object({ value: valueSchema(constraint) }),
          detail: {
            tags: ["Commands"],
            summary: `Set ${metric.label}`,
            description: `Write the "${metric.key}" setting. ${accepts}`,
          },
        },
        async ({ body, status }: { body: { value: number }; status: StatusFn }) => {
          try {
            await deps.write(metric.key, body.value);
          } catch (err) {
            // The generated body schema catches most bad values, but not the
            // enum and composite-control cases the funnel decides. Those are
            // still the caller's mistake, so this route must answer 400 like the
            // internal command endpoint does — not leak a 500.
            if (err instanceof WriteRejectedError) return status(400, { error: err.message });
            throw err;
          }
          return { ok: true, key: metric.key, value: body.value };
        },
      ) as unknown as Elysia;
    },
    app as unknown as Elysia,
  );
}
